/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Diego G. (https://sketchfab.com/empty_mirror)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/voxel-web-development-50ad959d6c6b4799806c45bfa46ca550
title: Voxel Web Development
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import myGLTF from "/models/development-transformed.glb"


export default function Develop(props) {
  // const { nodes, materials } = useGLTF('/models/development-transformed.glb')
  const { nodes, materials } = useGLTF(myGLTF)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_4.geometry} material={materials.palette} />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials['palette.001']} />
          </group>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.Object_8.geometry} material={materials['palette.002']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/development-transformed.glb')
