/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Lorenzo Penco (https://sketchfab.com/Eksmanen)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/thefuture-b5fda59eb51341a58da234c24074d2f0
title: TheFuture
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import myGLTF from "/models/future-transformed.glb"


export default function TheFuture(props) {
  // const { nodes, materials } = useGLTF('/models/future-transformed.glb')
  const { nodes, materials } = useGLTF(myGLTF)

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.capelliHIcapelliHIlambert2SG} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.capelliHIlambert1SG} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.capelliHIlambert1SG} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.lambert6SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.lambert7SG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.lambert7SG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.lambert7SG} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/future-transformed.glb')
