/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Vxcl (https://sketchfab.com/vxclhd)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/double-gulp-cup-42da6e2ac19b40f9b43e155ba23ac5b2
title: Double Gulp Cup
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function TheGulp(props) {
  const { nodes, materials } = useGLTF('/models/gulp-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={1.42}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.Object_5.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.Object_6.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.label} />
          </group>
          <group position={[0, 8.52, 0]} scale={1.91}>
            <mesh geometry={nodes.Object_9.geometry} material={materials.material} />
            <mesh geometry={nodes.Object_10.geometry} material={materials.material} />
          </group>
          <group scale={1.47}>
            <mesh geometry={nodes.Object_12.geometry} material={materials['Material.003']} />
          </group>
          <group position={[0, 6.86, 0]} rotation={[0, 0.71, 0]} scale={0.12}>
            <mesh geometry={nodes.Object_14.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Object_15.geometry} material={materials['Material.004']} />
            <mesh geometry={nodes.Object_16.geometry} material={materials.pink} />
            <mesh geometry={nodes.Object_17.geometry} material={materials.green} />
            <mesh geometry={nodes.Object_18.geometry} material={materials.yell} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/gulp-transformed.glb')
