/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Incg5764 (https://sketchfab.com/incg5764)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/casual-jar-of-raspberry-jam-61bc4a8ef3184b169ab368946fcf2135
title: Casual Jar of Raspberry Jam
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Jamjar(props) {
  const { nodes, materials } = useGLTF('/models/jamjar-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.main} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/jamjar-transformed.glb')
