/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Tiko (https://sketchfab.com/tikoavp)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/lyrical-lemonade-6330f01b2e3746dc8c1e84291400fd24
title: Lyrical Lemonade
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Lyric(props) {
  const { nodes, materials } = useGLTF('/models/lyric-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.CartonLP_Carton_0.geometry} material={materials.Carton} />
          </group>
          <group position={[0, 336.29, 46.47]} rotation={[-0.97, 0, 0]} scale={[6.84, 6.84, 100]}>
            <mesh geometry={nodes.Straw_Straw_0.geometry} material={materials.Straw} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/lyric-transformed.glb')
