/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: xenadus (https://sketchfab.com/xenadus)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
title: React logo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function LogoReact(props) {
  const { nodes, materials } = useGLTF('/models/react-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 7.94, 18.1]} rotation={[0, 0, -Math.PI / 2]} scale={[20.17, 39.17, 52.73]}>
            <mesh geometry={nodes['React-Logo_Material002_0'].geometry} material={materials['Material.002']} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/react-transformed.glb')
