/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: André Souza (https://sketchfab.com/asouza)
license: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
source: https://sketchfab.com/3d-models/sukunas-finger-0094c76440e3447a900797ede9bad5bf
title: Sukuna's finger
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SukunaFinger(props) {
  const { nodes, materials } = useGLTF('/models/sukunaFinger-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.lambert1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/sukunaFinger-transformed.glb')
