/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Fyrestar (https://sketchfab.com/mevedia)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/threejs-60320862bf904b7ab0e032c27daf7c7c
title: Three.js
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function LogoThreejs(props) {
  const { nodes, materials } = useGLTF('/models/threejs-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/threejs-transformed.glb')
